language: python
matrix:
  include:
    - python: 3.6
      env: TOXENV=py36
    - python: 3.7
      dist: xenial
      sudo: true
    - python: 2.7
      env: TOXENV=py27
before_install:
  - sudo apt-get update
  - sudo apt-get install meld
install:
  - pip install tox
script:
  - tox -c tox.ini
