name: Test StarterProject

on:
  workflow_dispatch:
  schedule:
    - cron: '45 16 * * 0'  # <https://crontab.guru/#45_16_*_*_0> - "At 16:45 UTC on Sunday"
    - cron: '30 18 * * 0'
    - cron: '30 19 * * 0'

jobs:
  call-workflow-passing-data:
    uses: approvals/ApprovalTests.Python.StarterProject/.github/workflows/test.yml@main